server:
    port: 80
    servlet:
        context-path: /api
spring:

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/myapp?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: ZJ123456

logging:
    level:
        org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace