server:
    port: 80
    servlet:
        context-path: /api
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://44.208.77.82:3306/myapp?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: admin
        password: ZIjing123

        # 指定类型为我们自己的
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            #druid 数据源专有配置
            # 初始化大小，最小，最大
            initialSize: 5
            minIdle: 5
            maxActive: 200
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 用来检测连接是否有效的sql，要求是一个查询语句
            validationQuery: SELECT 1 FROM DUAL
            # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
            testWhileIdle: true
            # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
            testOnBorrow: false
            # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            testOnReturn: false
            # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
            poolPreparedStatements: true
            # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
            max-pool-prepared-statement-per-connection-size: 50

    redis:
        host: 54.163.50.721
        password: 123456
        port: 6379
        timeout: 50000
        lettuce:
            pool:
                enabled: true
                # 连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池中的最小空闲连接
                min-idle: 1


#logging:
#    level:
#        org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

#配置日志输出
#mybatis-plus:
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl